### ISSUE TITLE
Projekte werden initial nicht geladen

### ISSUE THREAD

**Issue by olehmach** [pchorus/teamcity-monitor-dist#1]
Wir der Monitor gestartet, so werden die konfigurierten Projekte nicht sofort geladen, Stattdessen wird der Timer abgewartet. In dieser Zeit bleibt der Monitor schwarz.

**Comment by pchorus** [comment]
Das Laden der Projekte wird sofort ausgeführt (siehe Code Snippet). Das Laden kann allerdings schonmal länger dauern.

```
export class AppComponent {
  ...
  constructor(private http: Http, private elementRef: ElementRef) {
    // Here, getBuildTypes is called immediately
    Observable.concat(this.getBuildTypes(),
      Observable.interval(120000).flatMap(() => this.getBuildTypes()))
      .subscribe(buildTypes => {
        ...
      });
  }
}
```
